package com.example.Driver.service;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

import org.springframework.web.multipart.MultipartFile;

import com.example.Driver.DTO.DriverDTO;
import com.example.Driver.Entity.Driver;

public interface Driverservice {

	 
	
	  List<DriverDTO> findAll();

	  DriverDTO findById(int id);

	boolean delete(int id);

	DriverDTO update(DriverDTO driverDTO);

	/**
	 * Saves a new driver to the system.
	 * <p>
	 * This method converts the provided {@link DriverDTO} into a {@link Driver} entity,
	 * then persists it using the driver repository. It returns the saved Driver entity,
	 * including any autogenerated fields (like ID).
	 * </p>
	 *
	 * @param driverDTO The data transfer object containing driver details to be saved.
	 * @return The saved {@link Driver} entity.
	 */
	DriverDTO save(DriverDTO driverDTO, MultipartFile image, MultipartFile licence)throws IOException ;





		
	
}
