package com.example.Driver.service.impl;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;

import com.example.Driver.DTO.DriverDTO;
import com.example.Driver.Entity.Driver;
import com.example.Driver.Mappers.DriverMapper;
import com.example.Driver.repository.Driverrepository;
import com.example.Driver.service.Driverservice;

@Service
public class Driverserviceimpl implements Driverservice{
	private Driverrepository driverrepository;
	private DriverMapper driverMapper;
	
	public Driverserviceimpl(Driverrepository driverrepository,DriverMapper driverMapper) {
		this.driverrepository=driverrepository;
		this.driverMapper=driverMapper;
	}

	/**
	 * Saves a new driver to the system.
	 * <p>
	 * This method converts the provided {@link DriverDTO} into a {@link Driver} entity,
	 * then persists it using the driver repository. It returns the saved Driver entity,
	 * including any autogenerated fields (like ID).
	 * </p>
	 *
	 * @param driverDTO The data transfer object containing driver details to be saved.
	 * @return The saved {@link Driver} entity.
	 */
	@Override
	public DriverDTO save(DriverDTO driverDTO) {
				
		Driver driver =this.driverMapper.dtotoEntity(driverDTO);
		driver=driverrepository.save(driver);
		driverDTO=this.driverMapper.enitytoDto(driver);
		return driverDTO;
	}
	/**
	 * Retrieves all driver entities from the repository and maps them to DTOs.
	 *
	 * <p>This method fetches a list of all {@link Driver} entities stored in the database 
	 * via the {@code driverrepository}. It then converts each {@code Driver} entity into 
	 * a {@code DriverDTO} using the {@code driverMapper}, and returns the list of DTOs.</p>
	 *
	 * @return a list of {@link DriverDTO} objects representing all drivers in the system.
	 */
	@Override
	public List<DriverDTO> findAll() {
	    List<Driver> drivers = driverrepository.findAll();
	   return drivers.stream() 
	                  .map(driverMapper::enitytoDto)
	                  .collect(Collectors.toList());
	}

	/**
	 * Retrieves a driver by their unique ID.
	 * <p>
	 * This method searches for a {@link Driver} entity in the database using the provided ID.
	 * If the driver exists, it returns an {@link Optional} containing the driver; otherwise, it returns an empty {@link Optional}.
	 * </p>
	 *
	 * @param id The unique identifier of the driver to retrieve.
	 * @return An {@link Optional} containing the found {@link Driver} if it exists, or an empty {@link Optional} if not found.
	 */
	@Override
	public DriverDTO findById(int id) {
		// TODO Auto-generated method stub
		Optional<Driver> driverFound =driverrepository.findById(id);
		if(driverFound.isPresent()) {
			return this.driverMapper.enitytoDto(driverFound.get());
		}
		return null;
	}
	/**
	 * Deletes a driver by their unique ID.
	 * <p>
	 * This method removes the {@link Driver} entity with the specified ID from the database.
	 * If no driver exists with the provided ID, no action is performed.
	 * </p>
	 *
	 * @param id The unique identifier of the driver to be deleted.
	 * @return 
	 */
	@Override
	public boolean delete(int id) {
		try {
		driverrepository.deleteById(id);
		return true;
		}
		catch(Exception e) {
			return false;
		}
		
	}

	@Override
	public DriverDTO update(DriverDTO driverDTO) {
		  Driver existing = driverrepository.findById(driverDTO.getId()).orElse(null);
		    if (existing != null) {
		        existing.setName(driverDTO.getName());
		        existing.setEmail(driverDTO.getEmail());
		        existing.setAddress(driverDTO.getAddress());
		        existing.setVehicleNumber(driverDTO.getVehicleNumber());
		        existing.setImage(driverDTO.getImage());
		        existing.setJoindate(driverDTO.getJoindate());
		        existing.setLicence(driverDTO.getLicence());
		        existing.setStatus(driverDTO.getStatus());
		        existing.setVehicletype(driverDTO.getVehicletype());
		        
		        
		        driverrepository.save(existing);
		        return driverDTO;
		    } else {
		return null;
	}
	
	

	}

	
}
